theme: jekyll-theme-minimal
title: "Marek Grudzinski's Profile"
description: "„I'm a passionated software architect and an excited techy“"
logo: /assets/img/profile-img.jpg
google_analytics: "UA-3319420-3"

